In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
dataset = pd.read_csv(r"https://raw.githubusercontent.com/mk-gurucharan/Classification/master/IrisDataset.csv")

In [7]:
dataset

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [9]:
X = dataset.iloc[:,:4].values
y = dataset['species'].values

In [10]:
dataset.head(5)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [18]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [21]:
y_pred = classifier.predict(X_test)
y_pred

array(['setosa', 'setosa', 'setosa', 'versicolor', 'setosa', 'virginica',
       'virginica', 'virginica', 'virginica', 'setosa', 'versicolor',
       'setosa', 'setosa', 'setosa', 'versicolor', 'setosa', 'virginica',
       'virginica', 'virginica', 'setosa', 'virginica', 'versicolor',
       'virginica', 'virginica', 'setosa', 'versicolor', 'versicolor',
       'setosa', 'virginica', 'virginica'], dtype='<U10')

In [22]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))
cm

Accuracy :  0.8

array([[12,  0,  0],
       [ 0,  6,  6],
       [ 0,  0,  6]], dtype=int64)

In [23]:
df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df

   Real Values Predicted Values
0       setosa           setosa
1       setosa           setosa
2       setosa           setosa
3   versicolor       versicolor
4       setosa           setosa
5    virginica        virginica
6    virginica        virginica
7   versicolor        virginica
8   versicolor        virginica
9       setosa           setosa
10  versicolor       versicolor
11      setosa           setosa
12      setosa           setosa
13      setosa           setosa
14  versicolor       versicolor
15      setosa           setosa
16   virginica        virginica
17  versicolor        virginica
18   virginica        virginica
19      setosa           setosa
20   virginica        virginica
21  versicolor       versicolor
22  versicolor        virginica
23   virginica        virginica
24      setosa           setosa
25  versicolor       versicolor
26  versicolor       versicolor
27      setosa           setosa
28  versicolor        virginica
29  versicolor        virginica